#!/usr/bin/env python3
"""
Haseeb Autos — Demo builder
------------------------------------------------------------------
apps-script/*.html (Apps Script templates) ko resolve kar ke EK hi
self-contained demo/index.html banata hai jisme mock backend hota hai.

    python3 tools/build_demo.py

Output: demo/index.html   (koi CDN, koi network — direct browser mein khul jata hai)
"""
import os, re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

def gen_config_defs():
    """apps-script/Config.gs ka asli Settings schema JSON mein (mock_gs runtime ke zariye)."""
    import subprocess
    script = ROOT / "tools" / "gen_defs.js"
    if not script.exists():
        return ""
    try:
        out = subprocess.run(["node", str(script)], cwd=str(ROOT), capture_output=True,
                             text=True, timeout=180)
        if out.returncode == 0 and out.stdout.strip().startswith("["):
            return out.stdout.strip()
        print("  (settings schema: gen_defs failed — " + (out.stderr or "").strip()[:120] + ")")
    except Exception as e:
        print("  (settings schema: " + str(e)[:120] + ")")
    return ""


def backend_version() -> str:
    """Single source of truth: apps-script/Utils.gs → CONFIG.VERSION.

    Naya release? Bas Utils.gs me VERSION badhayein — service worker ka cache name,
    demo build tag aur zip version sab wahein se aa jayenge (purana cache auto-clear).
    """
    try:
        src = (ROOT / "apps-script" / "Utils.gs").read_text(encoding="utf-8")
        m = re.search(r"VERSION\s*:\s*['\"]([^'\"]+)['\"]", src)
        if m:
            return m.group(1)
    except Exception:
        pass
    return "0.0.0"

SRC = ROOT / "apps-script"
OUT = ROOT / "demo" / "index.html"
MOCK = ROOT / "demo" / "mock.js"
PRODUCTS = ROOT / "demo" / "products.js"

INCLUDE_RE = re.compile(r"<\?!=\s*include\('([^']+)'\)\s*;?\s*\?>")
PRINT_RE = re.compile(r"<\?=\s*([A-Za-z0-9_]+)\s*\?>")
# <?!= expr ?> — force print. Demo mein server value nahi hoti, is liye khaali
# JS string se badal do; warna literal `<?!= ... ?>` HTML mein reh jata aur
# script toot jati (smoke gate har console error par fail hota hai).
FORCE_RE = re.compile(r"<\?!=\s*[^?]*?\?>")

VALUES = {
    "title": "Haseeb Autos — ERP & POS (Demo)",
    "appVersion": backend_version() + "-demo",
    "serveMode": "demo",
    "apiUrl": "",
}


def render(text: str, depth: int = 0) -> str:
    if depth > 5:
        return text
    # <?!= include('X') ?>
    def repl(m):
        name = m.group(1)
        f = SRC / f"{name}.html"
        if not f.exists():
            return f"<!-- MISSING INCLUDE: {name} -->"
        return render(f.read_text(encoding="utf-8"), depth + 1)
    text = INCLUDE_RE.sub(repl, text)
    # <?= var ?>
    text = PRINT_RE.sub(lambda m: VALUES.get(m.group(1), ""), text)
    # <?!= expr ?> (include ke ilawa sab) → khaali JS string
    text = FORCE_RE.sub("''", text)
    return text


def main() -> int:
    index = (SRC / "Index.html").read_text(encoding="utf-8")
    html = render(index)

    anchor = '<script>\n    /* Injected by server template */'

    # real catalogue (list.pdf + barcode.pdf) must load BEFORE the mock backend
    if PRODUCTS.exists():
        prod = PRODUCTS.read_text(encoding="utf-8")
        pinject = ("<!-- ===== REAL PRODUCT CATALOG (list.pdf + barcode.pdf) ===== -->\n"
                   f"<script>\n{prod}\n</script>\n\n")
        if anchor in html:
            html = html.replace(anchor, pinject + anchor, 1)
        else:
            html = html.replace("</head>", pinject + "</head>", 1)

    # real Settings schema (Config.defs()) — demo kabhi source se alag na ho
    defs = gen_config_defs()
    if defs:
        dinject = ("<!-- ===== REAL SETTINGS SCHEMA (apps-script/Config.gs) ===== -->\n"
                   f"<script>\nwindow.CONFIG_DEFS_DEMO = {defs};\n</script>\n\n")
        if anchor in html:
            html = html.replace(anchor, dinject + anchor, 1)
        else:
            html = html.replace("</head>", dinject + "</head>", 1)

    if MOCK.exists():
        mock = MOCK.read_text(encoding="utf-8")
        # inject mock backend BEFORE app scripts so it is available at boot
        inject = ("<!-- ===== DEMO MOCK BACKEND (preview only) ===== -->\n"
                  f"<script>\n{mock}\n</script>\n\n")
        if anchor in html:
            html = html.replace(anchor, inject + anchor, 1)
        else:
            html = html.replace("</head>", inject + "</head>", 1)

    banner = ("<!--\n  HASEEB AUTOS — self-contained DEMO build.\n"
              "  Generated by tools/build_demo.py — DO NOT EDIT (edit apps-script/*.html instead).\n-->")
    html = banner + "\n" + html

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(html, encoding="utf-8")
    print(f"✔ Built {OUT.relative_to(ROOT)}  ({len(html)/1024:.1f} KB)")

    # ---- PWA assets (static hosting / installable mobile app) ----
    (OUT.parent / "manifest.webmanifest").write_text(MANIFEST, encoding="utf-8")
    sw = SERVICE_WORKER.replace("__VERSION__", backend_version())
    (OUT.parent / "sw.js").write_text(sw, encoding="utf-8")
    print("✔ Built demo/manifest.webmanifest + demo/sw.js  (PWA)")
    for n in (192, 512):
        icon_png = ROOT / "tools" / f"icon-{n}.png"          # source of truth (regenerate anytime)
        if icon_png.exists():
            (OUT.parent / f"icon-{n}.png").write_bytes(icon_png.read_bytes())
    missing = re.findall(r"MISSING INCLUDE: (\w+)", html)
    if missing:
        print("✖ Missing includes:", ", ".join(sorted(set(missing))))
        return 1
    return 0


# --------------------------------------------------------------------------
# PWA assets emitted next to demo/index.html
# --------------------------------------------------------------------------


_MANIFEST_ICONS = ",".join([
    '{"src":"icon-%d.png","sizes":"%dx%d","type":"image/png","purpose":"any maskable"}' % (n, n, n)
    for n in (192, 512)
])

MANIFEST = """{
  "name": "Haseeb Autos — ERP & POS",
  "short_name": "Haseeb Autos",
  "description": "Auto parts, car & bike decoration POS + ERP with AI assistant (3 branches, retail + wholesale).",
  "start_url": "./index.html",
  "scope": "./",
  "display": "standalone",
  "orientation": "any",
  "background_color": "#0b1220",
  "theme_color": "#0b1220",
  "lang": "en-PK",
  "dir": "ltr",
  "categories": ["business", "productivity", "shopping"],
  "icons": [%s],
  "shortcuts": [
    { "name": "New Sale (POS)", "url": "./index.html#/pos" },
    { "name": "Dashboard", "url": "./index.html#/dashboard" },
    { "name": "Stock / Inventory", "url": "./index.html#/inventory" },
    { "name": "Auto Reorder", "url": "./index.html#/reorder" }
  ]
}
""" % _MANIFEST_ICONS

SERVICE_WORKER = r"""/* HASEEB AUTOS — offline-first service worker (static hosting only)
 * - app shell (index.html + assets) cache-first  → app bina internet ke bhi khulti hai
 * - API calls (google.script.run / API_URL) hamesha network se
 * Naya build? CACHE name badlo → purana cache auto-clear ho jayega.            */
const CACHE = 'haseeb-autos-v__VERSION__';
const SHELL = ['./', './index.html', './manifest.webmanifest', './icon-192.png', './icon-512.png'];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL).catch(() => {})).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;                       // POST/API → network hi
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;             // cross-origin API → network
  if (/\/exec|\/dev|macro|api\?/i.test(url.pathname)) return;

  e.respondWith(
    fetch(req).then(res => {
      const copy = res.clone();
      caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {});
      return res;
    }).catch(() => caches.match(req).then(r => r || caches.match('./index.html')))
  );
});
"""


if __name__ == "__main__":
    sys.exit(main())
