#!/usr/bin/env python3
"""
Haseeb Autos — seed generator
================================================================================
Reads  tools/products.json  (produced by tools/import_products_csv.py from the
shop's real product export) and regenerates:

    • apps-script/Seed_Products.gs  → PRODUCT_SEED + one-click importer that also
                                      builds the masters (suppliers, brands,
                                      categories, custom fields) and stock rows
    • demo/products.js              → same catalogue for the offline demo mock

Nothing here invents prices: every rupee comes from the customer's CSV.

    python3 tools/gen_seed.py
"""
from __future__ import annotations

import datetime as dt
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = json.loads((ROOT / "tools" / "products.json").read_text(encoding="utf-8"))

STAMP = dt.datetime.now().strftime("%Y-%m-%d")

# short key -> JSON key.  Only non-empty values are emitted (keeps the file small).
FIELDS = [
    ("li", "lineItem"), ("cat", "category"), ("sub", "subCategory"),
    ("br", "brand"), ("md", "model"), ("og", "origin"), ("pg", "productGroup"),
    ("cl", "color"), ("ct", "costType"), ("put", "purchaseType"), ("sz", "size"),
    ("f", "conversionFactor"), ("sup", "supplier"), ("bc", "barcode"), ("ty", "partType"),
]
ALWAYS = ["c", "n", "cp", "wp", "rp", "ty", "bc"]


def js(v):
    return json.dumps(v, ensure_ascii=False)


def num(v):
    """Emit 270 not 270.0 — the sheet stays human-readable."""
    f = float(v)
    return str(int(f)) if f == int(f) else str(round(f, 2))


def record(p: dict) -> str:
    parts = [
        "c:" + js(p["code"]),
        "n:" + js(p["name"]),
    ]
    for short, key in FIELDS:
        v = p.get(key)
        if v in (None, "", 0) and short != "f":
            continue
        if short == "f":
            parts.append("f:" + str(int(v or 1)))
        else:
            parts.append(short + ":" + js(v))
    parts.append("cp:" + num(p.get("costPrice", 0)))
    parts.append("wp:" + num(p.get("wholesalePrice", 0)))
    parts.append("rp:" + num(p.get("retailPrice", 0)))
    return "  {" + ", ".join(parts) + "},"


# ------------------------------------------------------------------ metadata --
def meta() -> dict:
    li = sorted({p["lineItem"] for p in DATA})
    cats = sorted({(p["lineItem"], p["category"]) for p in DATA if p["category"]})
    return {
        "generated": STAMP,
        "products": len(DATA),
        "lineItems": len(li),
        "categories": len(cats),
        "subCategories": len({p["subCategory"] for p in DATA if p["subCategory"]}),
        "brands": len({p["brand"] for p in DATA if p["brand"]}),
        "suppliers": len({p["supplier"] for p in DATA if p["supplier"]}),
        "origins": len({p["origin"] for p in DATA if p["origin"]}),
        "barcodes": sum(1 for p in DATA if p["barcode"] and p["barcode"] != p["code"]),
    }


M = meta()

# --------------------------------------------------------------- Apps Script --
HEADER = """/**
 * HASEEB AUTOS — REAL PRODUCT SEED  (generated by tools/gen_seed.py — DO NOT EDIT)
 * =============================================================================
 * {products} products imported from the shop's own export ("product list2.csv"),
 * normalised by tools/import_products_csv.py into tools/products.json.
 *
 * Coverage: {lineItems} line items · {categories} categories · {subCategories} sub-categories ·
 *           {brands} brands · {suppliers} suppliers · {origins} origins · {barcodes} real barcodes.
 * Generated: {generated}
 *
 * -----------------------------------------------------------------------------
 * Apps Script editor mein chalayein:
 *     seedRealProducts()                 → sab kuch (masters + items + stock)
 *     seedRealProducts({{stock: 25}})      → opening stock 25 per branch
 *     seedRealProducts({{prices: false}})  → rates chhoday baghair sirf naye items add
 *     previewRealProducts()              → sirf log mein dekhein
 *
 * YEH IDEMPOTENT HAI — jitni baar bhi chalayein, duplicates nahi bantay:
 *   • items       → Product Code se match (mila to update, warna create)
 *   • suppliers/brands/categories → naam se match
 *   • stock rows  → (item, branch) se match; sirf ghaayab rows banti hain
 *   • koi bhi row delete nahi hoti
 *
 * Field map (CSV column → sheet column):
 *   Product Code→code · Product Name→name · Line Item→lineItem (L1) ·
 *   Category→category (L2) · Sub Category→subCategory (L3) · Brand→brand ·
 *   Model→model · Made in→origin · Conversion Factor→conversionFactor ·
 *   Size→size · Supplier→primarySupplierId (+Suppliers master) ·
 *   Cost/Wholesale/Retail Price→costPrice/wholesalePrice/retailPrice ·
 *   Barcode→barcode (blank ho to code) · Product Group / Color / Cost Type /
 *   Purchase Type → Items.customFields (JSON: cf_productGroup, cf_color,
 *   cf_costType, cf_purchaseType)
 * =============================================================================
 */

var SEED_META = {meta_json};

var PRODUCT_SEED = [
""".format(**M, meta_json=json.dumps(M, ensure_ascii=False))

SEEDER = r"""
/* ============================ one-click importer ========================== */
/**
 * opts: { stock, minStock, reorderLevel, prices, locations }
 *   stock         opening qty per branch for NEW items      (default 20)
 *   minStock      Items.minStock                            (default 5)
 *   reorderLevel  Items.reorderLevel                        (default 12)
 *   prices        existing items ke rates bhi update karein (default true)
 *   locations     sirf in branch IDs par stock dalen        (default: sab)
 */
function seedRealProducts(opts) {
  opts = opts || {};
  var dry = opts.dryRun === true;          /* true → sirf hisaab, koi write nahi */
  var stock = opts.stock === undefined ? 20 : opts.stock;
  var minStock = opts.minStock === undefined ? 5 : opts.minStock;
  var reorderLevel = opts.reorderLevel === undefined ? 12 : opts.reorderLevel;
  var withPrices = opts.prices !== false;
  var stamp = U.iso();

  var locs = DB.all('Locations').filter(function (l) {
    return !opts.locations || opts.locations.indexOf(l.id) > -1;
  });

  var itemsByCode = {}, suppliersByName = {}, brandsByName = {}, catsByKey = {}, stockByKey = {};
  DB.all('Items').forEach(function (i) { itemsByCode[U.norm(i.code)] = i; });
  DB.all('Suppliers').forEach(function (s) { suppliersByName[U.norm(s.name)] = s; });
  DB.all('Brands').forEach(function (b) { brandsByName[U.norm(b.name)] = b; });
  DB.all('Categories').forEach(function (c) { catsByKey[c.parentId + '|' + U.norm(c.name)] = c; });
  DB.all('Stock').forEach(function (s) { stockByKey[s.itemId + '|' + s.locationId] = s; });

  var r = { created: 0, updated: 0, unchanged: 0, suppliersCreated: 0, brandsCreated: 0,
            categoriesCreated: 0, customFieldsCreated: 0, stockRows: 0, total: PRODUCT_SEED.length };

  /* ---------- 1. custom field definitions (Product group / Color / Cost type) */
  [['productGroup', 'Product group', 'TEXT', 10], ['color', 'Color', 'TEXT', 11],
   ['costType', 'Cost type', 'SELECT', 12], ['purchaseType', 'Purchase type', 'TEXT', 13]]
    .forEach(function (d) {
      var found = DB.findOne('CustomFields', function (f) { return f.entity === 'ITEM' && f.key === d[0]; });
      if (found) return;
      Seed._put(dry, 'CustomFields', { id: U.uid('CF'), entity: 'ITEM', key: d[0], label: d[1],
        type: d[2], options: d[2] === 'SELECT' ? 'Fixed,Variable' : '', defaultValue: '',
        required: 'false', showInTable: 'false', showInForm: 'true', showInPos: 'false',
        tab: 'Extra fields', sortOrder: String(d[3]), active: 'true' });
      r.customFieldsCreated++;
    });

  /* ---------- 2. masters: line items (L1) + categories (L2) ----------------- */
  PRODUCT_SEED.forEach(function (p) {
    var li = U.str(p.li) || 'General';
    var l1 = Seed._cat(catsByKey, '', li, 'LINE', dry);
    if (l1.isNew) r.categoriesCreated++;
    if (U.str(p.cat)) {
      var l2 = Seed._cat(catsByKey, l1.row.id, p.cat, 'CAT', dry);
      if (l2.isNew) r.categoriesCreated++;
    }
  });

  /* ---------- 3. suppliers + brands ---------------------------------------- */
  PRODUCT_SEED.forEach(function (p) {
    if (U.str(p.sup) && !suppliersByName[U.norm(p.sup)]) {
      var s = Seed._put(dry, 'Suppliers', { id: U.uid('SUP'), code: 'SUP-' + U.pad(DB.count('Suppliers') + 1, 4),
        name: p.sup, phone: '', email: '', address: '', ntn: '', openingBalance: 0,
        paymentTerms: '30 days', notes: 'Auto-created by product import', active: 'true',
        customFields: '', createdAt: stamp });
      suppliersByName[U.norm(p.sup)] = s;
      r.suppliersCreated++;
    }
    if (U.str(p.br) && !brandsByName[U.norm(p.br)]) {
      var b = Seed._put(dry, 'Brands', { id: U.uid('BRD'), code: U.slug(p.br).substring(0, 8).toUpperCase(),
        name: p.br, notes: 'Auto-created by product import', active: 'true' });
      brandsByName[U.norm(p.br)] = b;
      r.brandsCreated++;
    }
  });

  /* ---------- 4. items (+ stock rows) -------------------------------------- */
  var toInsert = [], stockToInsert = [];

  PRODUCT_SEED.forEach(function (p) {
    var sup = suppliersByName[U.norm(p.sup || '')];
    var custom = {};
    if (U.str(p.pg)) custom.cf_productGroup = p.pg;
    if (U.str(p.cl)) custom.cf_color = p.cl;
    if (U.str(p.ct)) custom.cf_costType = p.ct;
    if (U.str(p.put)) custom.cf_purchaseType = p.put;

    var notes = [];
    if (U.str(p.sz)) notes.push('Size: ' + p.sz);
    if (U.str(p.md)) notes.push('Model: ' + p.md);
    if (U.str(p.og)) notes.push('Made in: ' + p.og);

    var detail = {
      name: p.n, lineItem: U.str(p.li) || 'General', category: U.str(p.cat),
      subCategory: U.str(p.sub), brand: U.str(p.br), model: U.str(p.md),
      origin: U.str(p.og), size: U.str(p.sz), conversionFactor: U.num(p.f, 1) || 1,
      unit: 'PCS', partType: U.str(p.ty) || 'OTHER',
      barcode: U.str(p.bc) || p.c, customFields: custom,
      primarySupplierId: sup ? sup.id : '',
      notes: notes.join(' · '), updatedAt: stamp
    };
    var price = { costPrice: p.cp, wholesalePrice: p.wp, retailPrice: p.rp, minPrice: p.cp };

    var found = itemsByCode[U.norm(p.c)];
    if (found) {
      var patch = {};
      Object.keys(detail).forEach(function (k) { patch[k] = detail[k]; });
      if (withPrices) Object.keys(price).forEach(function (k) { patch[k] = price[k]; });
      if (dry) { Seed._stock(found.id, locs, stockToInsert, stockByKey, p.cp, 0); r.updated++; return; }
      DB.update('Items', found.id, patch);
      r.updated++;
      Seed._stock(found.id, locs, stockToInsert, stockByKey, p.cp, 0);
      return;
    }

    var rec = { id: U.uid('ITM'), code: p.c, nameUr: '', make: '', yearFrom: '', yearTo: '',
      engine: '', chassis: '', altBarcodes: '', taxRate: 0, hsn: '',
      minStock: minStock, reorderLevel: reorderLevel, rack: '',
      defaultLocationId: locs[0] ? locs[0].id : '',
      trackSerial: 'false', hasExpiry: 'false', imageUrl: '', status: 'ACTIVE',
      createdAt: stamp, updatedAt: stamp };
    Object.keys(detail).forEach(function (k) { rec[k] = detail[k]; });
    Object.keys(price).forEach(function (k) { rec[k] = price[k]; });
    toInsert.push(rec);
    itemsByCode[U.norm(p.c)] = rec;
    r.created++;
    Seed._stock(rec.id, locs, stockToInsert, stockByKey, p.cp, stock);
  });

  r.stockRows = stockToInsert.length;

  if (dry) {
    r.dryRun = true;
    r.items = PRODUCT_SEED.map(function (p) {
      return { code: p.c, name: p.n, lineItem: U.str(p.li) || 'General', category: U.str(p.cat),
        subCategory: U.str(p.sub), brand: U.str(p.br), origin: U.str(p.og), size: U.str(p.sz),
        supplier: U.str(p.sup), barcode: U.str(p.bc) || p.c,
        costPrice: p.cp, wholesalePrice: p.wp, retailPrice: p.rp };
    });
    r.locations = locs.length;
    r.source = SEED_META;
    return r;
  }

  if (toInsert.length) DB.insertMany('Items', toInsert);
  if (stockToInsert.length) DB.insertMany('Stock', stockToInsert);
  DB.touch('Items'); DB.touch('Stock'); DB.touch('Categories'); DB.touch('Suppliers'); DB.touch('Brands');

  r.locations = locs.length;
  r.source = SEED_META;
  return r;
}

/* helpers (Seed.* — collision-free, seed-only) */
var Seed = {
  /** dry-run mein insert ki jagah sirf object banata hai (sheet par kuch nahi likhta) */
  _put: function (dry, sheet, rec) {
    return dry ? rec : DB.insert(sheet, rec);
  },

  /** category row by (parentId, name); create if missing */
  _cat: function (map, parentId, name, prefix, dry) {
    var key = parentId + '|' + U.norm(name);
    if (map[key]) return { row: map[key], isNew: false };
    var id = prefix + '-' + U.slug((parentId ? parentId + '-' : '') + name).toUpperCase().substring(0, 24);
    var rec = { id: id, code: U.slug(name).substring(0, 10).toUpperCase(),
      name: name, parentId: parentId, imageUrl: '',
      sortOrder: String(Object.keys(map).length + 1), active: 'true' };
    var row = Seed._put(dry, 'Categories', rec);
    map[key] = row;
    return { row: row, isNew: true };
  },

  /** queue a Stock row only when (itemId, locationId) is missing */
  _stock: function (itemId, locs, sink, map, avgCost, qty) {
    locs.forEach(function (loc) {
      var k = itemId + '|' + loc.id;
      if (map[k]) return;
      var row = { id: U.uid('STK'), itemId: itemId, locationId: loc.id, qty: String(qty),
        avgCost: String(avgCost || 0), rack: '', binId: '', lastCountedAt: '', updatedAt: U.iso() };
      sink.push(row);
      map[k] = row;
    });
  }
};

/** Sirf catalogue dekhne ke liye (logs mein) */
function previewRealProducts() {
  Logger.log('Products: ' + PRODUCT_SEED.length + '  meta: ' + JSON.stringify(SEED_META));
  Logger.log(PRODUCT_SEED.slice(0, 10));
  return PRODUCT_SEED.length;
}

/** Import se pehle CSV aur DB ka milan check karein (dry run) */
function auditRealProducts() {
  var byCode = {};
  DB.all('Items').forEach(function (i) { byCode[U.norm(i.code)] = i; });
  var missing = [], priceDiff = [];
  PRODUCT_SEED.forEach(function (p) {
    var it = byCode[U.norm(p.c)];
    if (!it) { missing.push(p.c); return; }
    if (U.num(it.retailPrice) !== U.num(p.rp) || U.num(it.costPrice) !== U.num(p.cp)) {
      priceDiff.push(p.c + ' db=' + it.costPrice + '/' + it.retailPrice + ' csv=' + p.cp + '/' + p.rp);
    }
  });
  var out = { csv: PRODUCT_SEED.length, missing: missing.length, missingCodes: missing.slice(0, 50),
              priceDiff: priceDiff.length, priceSamples: priceDiff.slice(0, 20) };
  Logger.log(JSON.stringify(out));
  return out;
}
"""

lines = [HEADER]
lines.extend(record(p) for p in DATA)
lines.append("];")
lines.append("")
lines.append(SEEDER)

out = ROOT / "apps-script" / "Seed_Products.gs"
out.write_text("\n".join(lines), encoding="utf-8")
print(f"✔ apps-script/Seed_Products.gs  ({len(DATA)} products, {out.stat().st_size:,} B)")

# ------------------------------------------------------------------- demo ----
demo = [
    "/* Real catalogue — generated by tools/gen_seed.py from tools/products.json.",
    f"   Source: product list2.csv · {len(DATA)} products · {M['lineItems']} line items. */",
    "window.PRODUCT_SEED = [",
]
for p in DATA:
    demo.append(
        "  {c:%s, n:%s, li:%s, cat:%s, sub:%s, br:%s, og:%s, sz:%s, sup:%s, bc:%s, cp:%s, wp:%s, rp:%s, f:%d, ty:%s},"
        % (js(p["code"]), js(p["name"]), js(p.get("lineItem", "")), js(p.get("category", "")),
           js(p.get("subCategory", "")), js(p.get("brand", "")), js(p.get("origin", "")),
           js(p.get("size", "")), js(p.get("supplier", "")), js(p["barcode"]),
           num(p.get("costPrice", 0)), num(p.get("wholesalePrice", 0)), num(p.get("retailPrice", 0)),
           int(p.get("conversionFactor") or 1), js(p.get("partType", "OTHER")))
    )
demo.append("];")
dp = ROOT / "demo" / "products.js"
dp.write_text("\n".join(demo), encoding="utf-8")
print(f"✔ demo/products.js  ({len(DATA)} products, {dp.stat().st_size:,} B)")
