const puppeteer=require('puppeteer');const assert=require('assert');const fs=require('fs');
(async()=>{const b=await puppeteer.launch({args:['--no-sandbox']});let n=0;const ok=(name,cond)=>{assert(cond,name);n++;console.log('PASS '+name);};try{const page=await b.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(require('url').pathToFileURL(require('path').join(__dirname,'../OPEN-WEBAPP.html')).href);
for(const w of [390,1024,1440]){await page.setViewport({width:w,height:900});ok(w+' no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));ok(w+' four usable app links',await page.evaluate(()=>[...document.querySelectorAll('a.launch')].every(a=>a.href.startsWith('https://script.google.com/macros/s/')&&a.getBoundingClientRect().height>=48)));}
const base=await page.$eval('#clean',e=>e.textContent);
async function set(v){await page.$eval('#url',(e,v)=>e.value=v,v);await page.click('#prepare');}
await set(base.replace('/macros/s/','/macros/u/2/s/')+'?authuser=2&sid=x&c=y#old');ok('account routes, reserved parameters and fragment removed',await page.$eval('#clean',(e,b)=>e.textContent===b,base));
ok('mobile route keys correct',await page.$$eval('a.launch',els=>JSON.stringify(els.map(a=>new URL(a.href).search))===JSON.stringify(['','?app=wh','?app=fo','?app=sm'])));
for(const url of ['javascript:alert(1)',base.replace('/exec','/dev'),'https://drive.google.com/file/d/a/view',base.replace('script.google.com','script.google.com.evil.example'),'https://user:pass@script.google.com/macros/s/abcdefghijklmnopqrst/exec']){await set(url);ok('reject invalid link '+url.slice(0,45),await page.evaluate(()=>document.querySelector('#ready').hidden&&!!document.querySelector('#error').textContent&&[...document.querySelectorAll('a.launch')].every(a=>!a.hasAttribute('href'))));}
await set(base);ok('clean URL remains unchanged',await page.$eval('#clean',(e,b)=>e.textContent===b,base));ok('no browser exceptions',errors.length===0);console.log('LAUNCHER: '+n+' PASS, 0 FAIL');}finally{await b.close();}})();
